### ISSUE TITLE
Does not work with YAML Front Matter

### ISSUE THREAD

**Issue by evan2m** [xdissent/jekyll-rst#2]
Not sure if I'm missing something here.  But when I render a .rst file, it does not render any of the content.

For instance:

```
--
layout: post
title: Hello

---

This is RST content
```

This renders an HTML page with the correct title but without any content.

**Comment by xdissent** [comment]
Make sure you've got docutils (and pygments) installed in a location accessible by Jekyll (works for me with Virtualenv). I just merged a patch that was screwing up docutils processing if the cache folder was missing, so please try with the latest version and see if that helps.

**Comment by evan2m** [comment]
Pulling SHA: 469e00b377e08734d2bf39871b89d11b42cb5704 fixed the issue.  RST is now rendering in pages and posts.

**Comment by xdissent** [comment]
Perfect. good luck!
